// Package router declares every route of the service.
package router

import (
	"time"

	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"

	_ "github.com/Cinema-Project-Juann/BackEnd-CP/docs" // swagger docs generated by `make swag`
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/config"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/handlers"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/middleware"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/models"
	apperrors "github.com/Cinema-Project-Juann/BackEnd-CP/pkg/errors"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/jwt"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/ratelimit"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/response"
)

// Handlers groups the handlers wired in main.
type Handlers struct {
	Health   *handlers.HealthHandler
	Auth     *handlers.AuthHandler
	User     *handlers.UserHandler
	Movie    *handlers.MovieHandler
	Batch    *handlers.BatchHandler
	Hall     *handlers.HallHandler
	Showtime *handlers.ShowtimeHandler
}

// New builds a gin.Engine with all middleware and routes attached.
func New(cfg *config.Config, db *gorm.DB, jwtManager *jwt.Manager, authLimiter, holdLimiter *ratelimit.Limiter, h Handlers) *gin.Engine {
	if cfg.App.IsProduction() {
		gin.SetMode(gin.ReleaseMode)
	}

	registerValidators()

	engine := gin.New()
	engine.RedirectTrailingSlash = false
	engine.Use(
		middleware.RequestID(),
		middleware.Recovery(),
		middleware.Logger(),
		middleware.CORS(cfg.CORS.AllowedOrigins),
	)

	engine.NoRoute(func(c *gin.Context) {
		response.Error(c, apperrors.NotFound("route not found"))
	})
	engine.NoMethod(func(c *gin.Context) {
		response.Error(c, apperrors.BadRequest("method not allowed"))
	})

	// Infrastructure probes for k8s/docker healthchecks.
	engine.GET("/health", h.Health.Check)
	engine.GET("/healthz", h.Health.Healthz)

	if !cfg.App.IsProduction() {
		engine.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))
	}

	// DBGuard answers 503 fast when the DB is down.
	v1 := engine.Group("/api/v1")
	v1.Use(middleware.DBGuard(db, 500*time.Millisecond))
	v1.GET("/health", h.Health.Check)

	auth := v1.Group("/auth")
	auth.Use(middleware.RateLimit(authLimiter))
	{
		// Auth routes are public: the audit middleware only stashes IP and
		// user agent; services fill actor after a successful login/register,
		// the failure path logs rejected attempts.
		auth.POST("/register", middleware.Audit(db, "auth.register", "user"), h.Auth.Register)
		auth.POST("/login", middleware.Audit(db, "auth.login", "user"), h.Auth.Login)
		auth.POST("/refresh", middleware.Audit(db, "auth.refresh", "user"), h.Auth.Refresh)
	}

	protected := v1.Group("")
	protected.Use(middleware.Auth(jwtManager))
	{
		protected.GET("/users/me", h.User.Me)

		// Customer views.
		protected.GET("/movies/:id/showtimes", h.Showtime.ListForMovie)
		protected.GET("/shows/:id/seats", h.Showtime.SeatMap)

		movies := protected.Group("/movies")
		{
			movies.GET("", h.Movie.List)
			movies.GET("/:id", h.Movie.Detail)

			// Writes are admin/staff only. Audit runs before role checks so
			// forbidden attempts on an authenticated route are logged too.
			movies.POST("", middleware.Audit(db, "admin.create_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Create)
			movies.PUT("/:id", middleware.Audit(db, "admin.update_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Update)
			movies.DELETE("/:id", middleware.Audit(db, "admin.delete_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Delete)
		}

		// Hall and showtime management: admin/staff only.
		catalog := protected.Group("/admin")
		{
			catalog.GET("/halls", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.List)
			catalog.GET("/halls/:id", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Show)
			catalog.GET("/halls/:id/seats", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Seats)
			catalog.GET("/halls/:id/prices", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Prices)
			catalog.POST("/halls", middleware.Audit(db, "admin.create_hall", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Create)
			catalog.PUT("/halls/:id/seats/:seatId", middleware.Audit(db, "admin.update_hall_seat", "seat"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.UpdateSeat)
			catalog.PUT("/halls/:id/prices", middleware.Audit(db, "admin.set_hall_prices", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.SetPrices)
			catalog.POST("/showtimes", middleware.Audit(db, "admin.create_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Create)
			catalog.PUT("/showtimes/:id", middleware.Audit(db, "admin.update_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Update)
			catalog.DELETE("/showtimes/:id", middleware.Audit(db, "admin.delete_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Delete)
		}

		// System administration: batch logs, manual job runs (admin only).
		admin := protected.Group("/admin")
		admin.Use(middleware.RequireRoles(models.RoleAdmin))
		{
			admin.GET("/batch/jobs", h.Batch.List)
		}
		admin.POST("/batch/jobs/:name/run", middleware.Audit(db, "admin.run_job", "batch_job"), middleware.RequireRoles(models.RoleAdmin), h.Batch.Run)
	}

	// holdLimiter is wired to the /orders/hold group when F7 lands.
	_ = holdLimiter

	return engine
}