// Package router declares every route of the service.
package router

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"

	_ "github.com/Cinema-Project-Juann/BackEnd-CP/docs" // swagger docs generated by `make swag`
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/config"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/handlers"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/middleware"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/models"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/payment"
	"github.com/Cinema-Project-Juann/BackEnd-CP/internal/storage"
	apperrors "github.com/Cinema-Project-Juann/BackEnd-CP/pkg/errors"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/jwt"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/ratelimit"
	"github.com/Cinema-Project-Juann/BackEnd-CP/pkg/response"
)

type Handlers struct {
	Health     *handlers.HealthHandler
	Auth       *handlers.AuthHandler
	User       *handlers.UserHandler
	Movie      *handlers.MovieHandler
	Batch      *handlers.BatchHandler
	Hall       *handlers.HallHandler
	Showtime   *handlers.ShowtimeHandler
	Booking    *handlers.BookingHandler
	SSE        *handlers.SSEHandler
	Payment    *handlers.PaymentHandler
	Staff      *handlers.StaffHandler
	Report     *handlers.ReportHandler
	Media      *handlers.MediaHandler
	Audit      *handlers.AuditHandler
	Voucher    *handlers.VoucherHandler
	Membership *handlers.MembershipHandler
	Combo      *handlers.ComboHandler
	Article    *handlers.ArticleHandler
	Owner      *handlers.OwnerHandler
	Loyalty    *handlers.LoyaltyHandler
	Ledger     *handlers.LedgerHandler
	Waitlist   *handlers.WaitlistHandler
	Pricing    *handlers.PricingRuleHandler
	Branch     *handlers.BranchHandler
	Queue      *handlers.QueueHandler
}

type Limiters struct {
	Auth   *ratelimit.Limiter
	Hold   *ratelimit.Limiter
	Public *ratelimit.Limiter
	Events *ratelimit.Limiter
}

func New(cfg *config.Config, db *gorm.DB, jwtManager *jwt.Manager, accounts middleware.AccountChecker,
	limits Limiters, payments *payment.Registry, perms middleware.PermissionChecker, h Handlers) *gin.Engine {
	if cfg.App.IsProduction() {
		gin.SetMode(gin.ReleaseMode)
	}

	registerValidators()

	engine := gin.New()
	engine.RedirectTrailingSlash = false
	// Only configured proxies may set X-Forwarded-For, so rate limits and the
	// login lockout can not be dodged with a forged header.
	if err := engine.SetTrustedProxies(cfg.Server.TrustedProxies); err != nil {
		_ = engine.SetTrustedProxies(nil)
	}
	engine.Use(
		middleware.RequestID(),
		middleware.Recovery(),
		middleware.SecurityHeaders(),
		middleware.BodyLimit(cfg.Server.MaxBodyBytes),
		middleware.Logger(),
		middleware.CORS(cfg.CORS.AllowedOrigins),
	)

	engine.NoRoute(func(c *gin.Context) {
		response.Error(c, apperrors.NotFound("route not found"))
	})
	engine.NoMethod(func(c *gin.Context) {
		response.Error(c, apperrors.BadRequest("method not allowed"))
	})

	engine.GET("/health", h.Health.Check)
	engine.GET("/healthz", h.Health.Healthz)

	if dir := h.Media.LocalDir(); dir != "" {
		engine.Static(storage.MediaPath, dir)
	}

	if !cfg.App.IsProduction() {
		engine.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))
	}

	v1 := engine.Group("/api/v1")
	v1.Use(middleware.DBGuard(db, 500*time.Millisecond), middleware.NoStore())
	v1.GET("/health", h.Health.Check)
	v1.GET("/healthz", h.Health.Healthz)

	auth := v1.Group("/auth")
	auth.Use(middleware.RateLimit(limits.Auth))
	{
		// No user yet: Audit only stashes IP and user agent; services fill the actor on success.
		auth.POST("/register", middleware.Audit(db, "auth.register", "user"), h.Auth.Register)
		auth.POST("/login", middleware.Audit(db, "auth.login", "user"), h.Auth.Login)
		auth.POST("/terms-accept", middleware.Audit(db, "auth.accept_terms", "user"), h.Auth.AcceptTerms)
		auth.POST("/refresh", middleware.Audit(db, "auth.refresh", "user"), h.Auth.Refresh)
		auth.POST("/logout", middleware.Audit(db, "auth.logout", "user"), h.Auth.Logout)
		auth.POST("/forgot-password", middleware.Audit(db, "auth.forgot_password", "user"), h.Auth.ForgotPassword)
		auth.POST("/reset-password", middleware.Audit(db, "auth.reset_password", "user"), h.Auth.ResetPassword)
	}

	public := v1.Group("")
	public.Use(middleware.RateLimit(limits.Public), middleware.OptionalAuth(jwtManager, accounts))
	{
		public.GET("/movies", h.Movie.List)
		public.GET("/movies/:id", h.Movie.Detail)
		public.GET("/movies/:id/showtimes", h.Showtime.ListForMovie)
		public.GET("/showtimes", h.Showtime.List)
		public.GET("/combos", h.Combo.ListPublic)
		public.GET("/membership-tiers", h.Membership.ListTiers)
		public.GET("/articles", h.Article.List)
		public.GET("/articles/:slug", h.Article.Show)
		public.GET("/rewards", h.Loyalty.ListRewards)
		public.GET("/branches", h.Branch.List)
	}

	protected := v1.Group("")
	protected.Use(middleware.Auth(jwtManager, accounts))
	{
		protected.GET("/users/me", h.User.Me)
		protected.PUT("/users/me", middleware.Audit(db, "users.update_profile", "user"), h.User.UpdateMe)
		// Account erasure is a customer self-service right; staff/admin are
		// operational accounts managed by an admin (lock/unlock), not self-erased.
		protected.DELETE("/users/me", middleware.Audit(db, "users.delete_me", "user"),
			middleware.RequireRoles(models.RoleCustomer), h.User.DeleteMe)
		protected.PUT("/users/me/password", middleware.Audit(db, "users.change_password", "user"), h.Auth.ChangePassword)

		protected.GET("/shows/:id/seats", h.Showtime.SeatMap)
		protected.GET("/shows/:id/seats/suggest", h.Showtime.SuggestSeats)

		movies := protected.Group("/movies")
		{
			// Audit runs before role checks so forbidden attempts are logged too.
			movies.POST("", middleware.Audit(db, "admin.create_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Create)
			movies.PUT("/:id", middleware.Audit(db, "admin.update_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Update)
			movies.DELETE("/:id", middleware.Audit(db, "admin.delete_movie", "movie"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Movie.Delete)
		}

		catalog := protected.Group("/admin")
		{
			catalog.GET("/hall-templates", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Templates)
			catalog.GET("/halls", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.List)
			catalog.GET("/halls/:id", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Show)
			catalog.GET("/halls/:id/seats", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Seats)
			catalog.GET("/halls/:id/prices", middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Prices)
			catalog.POST("/halls", middleware.Audit(db, "admin.create_hall", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Create)
			catalog.POST("/halls/:id/clone", middleware.Audit(db, "admin.clone_hall", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.Clone)
			catalog.PUT("/halls/:id", middleware.Audit(db, "admin.update_hall", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.UpdateHall)
			catalog.PUT("/halls/:id/layout", middleware.Audit(db, "admin.update_hall_layout", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.RegenerateLayout)
			catalog.DELETE("/halls/:id", middleware.Audit(db, "admin.delete_hall", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.DeleteHall)
			catalog.PATCH("/halls/:id/seats", middleware.Audit(db, "admin.bulk_update_seats", "seat"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.BulkUpdateSeats)
			catalog.PUT("/halls/:id/seats/:seatId", middleware.Audit(db, "admin.update_hall_seat", "seat"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.UpdateSeat)
			catalog.PUT("/halls/:id/prices", middleware.Audit(db, "admin.set_hall_prices", "hall"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.SetPrices)
			catalog.POST("/showtimes", middleware.Audit(db, "admin.create_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Create)
			catalog.PUT("/showtimes/:id", middleware.Audit(db, "admin.update_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Update)
			catalog.DELETE("/showtimes/:id", middleware.Audit(db, "admin.delete_showtime", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.Delete)
			catalog.PUT("/showtimes/:id/queue", middleware.Audit(db, "admin.set_showtime_queue", "showtime"), middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Showtime.SetQueueEnabled)
		}

		orders := protected.Group("/orders")
		{
			orders.GET("", h.Booking.List)
			orders.POST("/hold", middleware.RateLimit(limits.Hold), middleware.Audit(db, "orders.hold", "booking"),
				middleware.RequireRoles(models.RoleCustomer), h.Booking.Hold)
			orders.POST("/:id/pay", middleware.Audit(db, "orders.pay", "booking"),
				middleware.RequireRoles(models.RoleCustomer), h.Booking.Pay)
			orders.POST("/:id/confirm", middleware.Audit(db, "orders.confirm", "booking"),
				middleware.RequireRoles(models.RoleCustomer), h.Booking.Confirm)
			orders.POST("/:id/cancel", middleware.Audit(db, "orders.cancel", "booking"),
				middleware.RequireRoles(models.RoleCustomer), h.Booking.Cancel)
			orders.GET("/:id/status", middleware.RequireRoles(models.RoleCustomer), h.Booking.Status)
			orders.GET("/:id", middleware.RequireRoles(models.RoleCustomer), h.Booking.Order)
			orders.GET("/:id/tickets", middleware.RequireRoles(models.RoleCustomer), h.Booking.Order)
		}

		tickets := protected.Group("/tickets")
		{
			tickets.POST("/:id/redeem", middleware.Audit(db, "staff.redeem_ticket", "ticket"),
				middleware.RequireRoles(models.RoleStaff, models.RoleAdmin), h.Booking.Redeem)
		}

		memberships := protected.Group("/memberships")
		memberships.Use(middleware.RequireRoles(models.RoleCustomer))
		{
			memberships.POST("/purchase", middleware.Audit(db, "orders.purchase_membership", "user_membership"), h.Membership.Purchase)
			memberships.GET("/me", h.Membership.My)
		}

		queue := protected.Group("/queue")
		queue.Use(middleware.RequireRoles(models.RoleCustomer))
		{
			queue.POST("/join", h.Queue.Join)
			queue.GET("/status", h.Queue.Status)
		}

		waitlist := protected.Group("/waitlist")
		waitlist.Use(middleware.RequireRoles(models.RoleCustomer))
		{
			waitlist.POST("", middleware.Audit(db, "orders.join_waitlist", "waitlist_entry"), h.Waitlist.Join)
			waitlist.DELETE("/:id", middleware.Audit(db, "orders.cancel_waitlist", "waitlist_entry"), h.Waitlist.Cancel)
			waitlist.GET("/me", h.Waitlist.My)
		}

		loyalty := protected.Group("/loyalty")
		loyalty.Use(middleware.RequireRoles(models.RoleCustomer))
		{
			loyalty.GET("/points", h.Loyalty.Balance)
			loyalty.GET("/points/transactions", h.Loyalty.Transactions)
		}
		protected.POST("/rewards/:id/redeem", middleware.Audit(db, "orders.redeem_reward", "reward_redemption"),
			middleware.RequireRoles(models.RoleCustomer), h.Loyalty.Redeem)

		protected.GET("/events/token", middleware.RateLimitByUser(limits.Events), h.SSE.IssueToken)

		protected.GET("/payments/providers", h.Payment.Providers)

		staff := protected.Group("/staff")
		staff.Use(middleware.RequireRoles(models.RoleStaff, models.RoleAdmin))
		{
			staff.GET("/dashboard", h.Staff.Dashboard)
			staff.GET("/overview", h.Staff.Overview)
			staff.GET("/boxoffice/day", h.Staff.BoxOfficeDay)
			// Same action name as the success row the service writes in-transaction
			// (orders.counter_sell) — filtering by action must show both outcomes.
			staff.POST("/orders", middleware.Audit(db, "orders.counter_sell", "booking"), h.Staff.CounterSell)
			staff.GET("/orders/:id", h.Staff.OrderDetail)
			staff.POST("/orders/:id/resend-email", middleware.Audit(db, "staff.resend_ticket_email", "booking"), h.Staff.ResendTicketEmail)
			staff.GET("/showtimes/:id/tickets", h.Staff.Tickets)
			// Customer support lookup: read-only, scoped to role=customer accounts
			// only (staff/admin accounts stay visible only via /admin/users).
			staff.GET("/customers", h.Staff.SearchCustomers)
			staff.GET("/customers/:id", h.Staff.CustomerProfile)
			staff.GET("/customers/:id/orders", h.Staff.CustomerOrders)
			staff.POST("/rewards/:code/deliver", middleware.Audit(db, "staff.deliver_reward", "reward_redemption"), h.Loyalty.MarkDelivered)
		}

		protected.GET("/admin/users", middleware.RequireRoles(models.RoleAdmin), h.User.List)
		protected.POST("/admin/users", middleware.Audit(db, "admin.create_user", "user"),
			middleware.RequireRoles(models.RoleAdmin), h.User.Create)
		protected.PATCH("/admin/users/:id", middleware.Audit(db, "admin.update_user", "user"),
			middleware.RequireRoles(models.RoleAdmin), h.User.Update)
		protected.PUT("/admin/users/:id", middleware.Audit(db, "admin.update_user", "user"),
			middleware.RequireRoles(models.RoleAdmin), h.User.Update)

		protected.GET("/admin/reports/daily", middleware.RequireRoles(models.RoleAdmin), h.Report.Daily)
		protected.GET("/admin/reports/export.xlsx", middleware.Audit(db, "admin.export_report", "report"),
			middleware.RequireRoles(models.RoleAdmin), h.Report.ExportXLSX)
		protected.GET("/admin/overview", middleware.RequireRoles(models.RoleAdmin), h.Report.Overview)

		// Aliases required by the API contract; the seat grid is readable by any signed-in user.
		halls := protected.Group("/halls")
		{
			halls.GET("/:id/seats", h.Hall.Seats)
			halls.PUT("/:id/seats/:seatId", middleware.Audit(db, "admin.update_hall_seat", "seat"),
				middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.UpdateSeat)
			halls.PUT("/:id/prices", middleware.Audit(db, "admin.set_hall_prices", "hall"),
				middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Hall.SetPrices)
		}

		protected.POST("/admin/uploads/poster", middleware.Audit(db, "admin.upload_poster", "media"),
			middleware.RequireRoles(models.RoleAdmin, models.RoleStaff), h.Media.UploadPoster)

		admin := protected.Group("/admin")
		admin.Use(middleware.RequireRoles(models.RoleAdmin))
		{
			admin.GET("/batch/jobs", h.Batch.List)
			admin.GET("/audit-logs", h.Audit.List)
		}
		admin.POST("/batch/jobs/:name/run", middleware.Audit(db, "admin.run_job", "batch_job"), middleware.RequireRoles(models.RoleAdmin), h.Batch.Run)

		// Deny-by-default (Phần 9.2): role=admin alone is not enough below —
		// pricing/content is also required from admin_permissions, granted only
		// by an owner. role=owner always passes (middleware.RequirePermission).
		pricing := protected.Group("/admin")
		pricing.Use(middleware.RequireRoles(models.RoleAdmin, models.RoleOwner), middleware.RequirePermission(perms, models.PermissionPricing))
		{
			pricing.GET("/vouchers", h.Voucher.List)
			pricing.GET("/vouchers/conflicts", h.Voucher.Conflicts)
			pricing.GET("/vouchers/:id", h.Voucher.Show)
			pricing.POST("/vouchers", middleware.Audit(db, "admin.create_voucher", "voucher"), h.Voucher.Create)
			pricing.PUT("/vouchers/:id", middleware.Audit(db, "admin.update_voucher", "voucher"), h.Voucher.Update)
			pricing.PUT("/vouchers/:id/status", middleware.Audit(db, "admin.set_voucher_status", "voucher"), h.Voucher.SetStatus)

			pricing.GET("/membership-tiers", h.Membership.ListTiersAdmin)
			pricing.POST("/membership-tiers", middleware.Audit(db, "admin.create_membership_tier", "membership_tier"), h.Membership.CreateTier)
			pricing.PUT("/membership-tiers/:id", middleware.Audit(db, "admin.update_membership_tier", "membership_tier"), h.Membership.UpdateTier)

			pricing.GET("/combos", h.Combo.List)
			pricing.GET("/combos/:id", h.Combo.Show)
			pricing.POST("/combos", middleware.Audit(db, "admin.create_combo", "combo"), h.Combo.Create)
			pricing.PUT("/combos/:id", middleware.Audit(db, "admin.update_combo", "combo"), h.Combo.Update)
			pricing.PUT("/combos/:id/stock", middleware.Audit(db, "admin.set_combo_stock", "combo"), h.Combo.SetStock)

			pricing.GET("/rewards", h.Loyalty.ListRewardsAdmin)
			pricing.POST("/rewards", middleware.Audit(db, "admin.create_reward", "reward"), h.Loyalty.CreateReward)
			pricing.PUT("/rewards/:id", middleware.Audit(db, "admin.update_reward", "reward"), h.Loyalty.UpdateReward)

			pricing.GET("/pricing-rules", h.Pricing.List)
			pricing.POST("/pricing-rules", middleware.Audit(db, "admin.create_pricing_rule", "pricing_rule"), h.Pricing.Create)
			pricing.PUT("/pricing-rules/:id", middleware.Audit(db, "admin.update_pricing_rule", "pricing_rule"), h.Pricing.Update)
		}

		finance := protected.Group("/admin")
		finance.Use(middleware.RequireRoles(models.RoleAdmin, models.RoleOwner), middleware.RequirePermission(perms, models.PermissionFinance))
		{
			finance.GET("/ledger/summary", h.Ledger.Summary)
		}

		content := protected.Group("/admin")
		content.Use(middleware.RequireRoles(models.RoleAdmin, models.RoleOwner), middleware.RequirePermission(perms, models.PermissionContent))
		{
			content.GET("/articles", h.Article.ListAdmin)
			content.GET("/articles/:id", h.Article.ShowAdmin)
			content.POST("/articles", middleware.Audit(db, "admin.create_article", "article"), h.Article.Create)
			content.PUT("/articles/:id", middleware.Audit(db, "admin.update_article", "article"), h.Article.Update)
			content.DELETE("/articles/:id", middleware.Audit(db, "admin.delete_article", "article"), h.Article.Delete)

			content.GET("/branches", h.Branch.ListAdmin)
			content.POST("/branches", middleware.Audit(db, "admin.create_branch", "branch"), h.Branch.Create)
			content.PUT("/branches/:id", middleware.Audit(db, "admin.update_branch", "branch"), h.Branch.Update)
		}

		owner := protected.Group("/admin/owners")
		owner.Use(middleware.RequireRoles(models.RoleOwner))
		{
			owner.PATCH("/:id", middleware.Audit(db, "owner.set_owner", "user"), h.Owner.SetOwner)
			owner.GET("/:id/permissions", h.Owner.ListPermissions)
			owner.POST("/:id/permissions", middleware.Audit(db, "owner.grant_permission", "admin_permission"), h.Owner.GrantPermission)
			owner.DELETE("/:id/permissions/:key", middleware.Audit(db, "owner.revoke_permission", "admin_permission"), h.Owner.RevokePermission)
		}
	}

	// EventSource can not send an Authorization header, so the realtime token in the URL is the credential.
	v1.GET("/events/shows/:id", h.SSE.Stream)

	// No JWT: the provider signature is the credential. Some gateways call the IPN with GET, others POST.
	v1.Match([]string{http.MethodGet, http.MethodPost}, "/payments/:provider/ipn", h.Payment.Notify)
	v1.GET("/payments/:provider/return", h.Payment.Return)

	for _, p := range payments.List() {
		if sim, ok := p.(payment.Simulator); ok {
			engine.Any(sim.SimulatorPath()+"/*path", gin.WrapH(sim.SimulatorHandler()))
		}
	}

	return engine
}
